export enum CategoriaDespesaEnum {
  COMBUSTIVEL = 'COMBUSTIVEL',
  DIVULGACAO = 'DIVULGACAO',
  ALIMENTACAO = 'ALIMENTACAO',
  PASSAGENS = 'PASSAGENS',
  MATERIAL_ESCRITORIO = 'MATERIAL_ESCRITORIO',
}